module.exports = [
  "steancommunity",
  "stearncommunytiy",
  "steancommunnity",
  "steamcommunytu",
  "steamcomunitty",
  "steancommunytiu",
  "steancommunyti",
  "tradeoffer/new/?partner=",
  "new/?partner=",
  "tradeoffer/new",
  "tradeoffer",
  "leaving cs:go",
  "giving away my skins to people",
  "skins to people",
  "giving away my skins",
  "3 knifes",
  "don't be greedy",
  "tournament-predator",
  "http-webs-roblox",
  "gofundme",
  "rollskin",
  "balashcourse",
  "axo2moon",
  "discord.gg",
  "discorcl",
  "steamcommunity",
  "discord-nitro",
  "discord-faq",
];
